blank_issues_enabled: false
contact_links:
  - name: General questions
    url: https://github.com/ubehera/agent-forge
    about: For non-licensing questions, open an issue using a clear title and description.
